from __future__ import annotations

from pathlib import Path
from typing import Iterable

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors

from billing_engine.models import Customer, Invoice, InvoiceLineItem


class InvoiceRenderer:

    def __init__(self, output_dir: str | Path = "invoices") -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def render(
        self,
        invoice: Invoice,
        customer: Customer,
        line_items: Iterable[InvoiceLineItem],
    ) -> Path:
        file_path = self.output_dir / f"INV-{invoice.id or 'DRAFT'}.pdf"
        c = canvas.Canvas(str(file_path), pagesize=A4)
        
        width, height = A4
        
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 60, "INVOICE")
        
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.HexColor("#555555"))
        c.drawRightString(width - 50, height - 50, f"Invoice ID: #{invoice.id or 'DRAFT'}")
        
        issued_date = getattr(invoice, "issued_at", None) or invoice.period_start.isoformat()
        c.drawRightString(width - 50, height - 65, f"Date: {issued_date}")
        
        c.setStrokeColor(colors.HexColor("#CCCCCC"))
        c.setLineWidth(1)
        c.line(50, height - 85, width - 50, height - 85)
        
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 115, "Bill To:")
        
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 130, customer.name)
        c.drawString(50, height - 145, customer.email)
        
        country = getattr(customer, "tax_country", getattr(customer, "country_code", ""))
        state = getattr(customer, "tax_state", getattr(customer, "state_code", ""))
        location = f"{state}, {country}" if state else country
        c.drawString(50, height - 160, location)
        
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColor(colors.HexColor("#444444"))
        c.drawString(50, height - 190, f"Billing Period: {invoice.period_start} to {invoice.period_end}")
        
        y = height - 230
        c.setFillColor(colors.HexColor("#EEEEEE"))
        c.rect(50, y, width - 100, 20, fill=True, stroke=False)
        
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(60, y + 6, "Description")
        c.drawRightString(width - 60, y + 6, "Amount")
        
        c.setFont("Helvetica", 10)
        for item in line_items:
            y -= 25
            if y < 80: 
                c.showPage()
                y = height - 60
                c.setFont("Helvetica", 10)
                
            c.drawString(60, y, item.description)
            c.drawRightString(width - 60, y, item.amount.to_storage())
            
        y -= 20
        c.setStrokeColor(colors.HexColor("#E0E0E0"))
        c.line(50, y, width - 50, y)
        
        y -= 20
        c.drawString(width - 200, y, "Subtotal:")
        c.drawRightString(width - 60, y, invoice.subtotal.to_storage())
        
        y -= 15
        c.drawString(width - 200, y, "Discount:")
        c.drawRightString(width - 60, y, f"-{invoice.discount_total.to_storage()}")
        
        y -= 15
        c.drawString(width - 200, y, "Tax:")
        c.drawRightString(width - 60, y, invoice.tax_total.to_storage())
        
        y -= 25
        c.setFont("Helvetica-Bold", 12)
        c.drawString(width - 200, y, "TOTAL:")
        c.drawRightString(width - 60, y, invoice.total_amount.to_storage())
        
        c.setFont("Helvetica", 8)
        c.setFillColor(colors.HexColor("#888888"))
        c.drawCentredString(width / 2.0, 40, "Generated by Billing Engine")
        
        c.save()
        return file_path.resolve()